parameter_defaults:
    # -------------------------------------------------------------------------
    # Control Plane subnet is used to get the VIPs,
    #    VIPs need to be on same network as controllers.
    # -------------------------------------------------------------------------
    ControlPlaneSubnet: ctlplane-leaf1

    NeutronBridgeMappings: datacentre:br-ex,tenant:br-isolated
    NeutronExternalNetworkBridge: ''
    NeutronNetworkType: vxlan
    NeutronNetworkVLANRanges: tenant:1000:2000
    NeutronTunnelTypes: vxlan

    # NetworkDeploymentActions: ['CREATE','UPDATE']

resource_registry:
    # Controller Nodes
    # OS::TripleO::Controller::Net::SoftwareConfig: /home/centos/tripleo-heat-templates/network/config/multiple-nics/controller.yaml
    OS::TripleO::Controller::Net::SoftwareConfig: /home/centos/overcloud/templates/controller.yaml
    # Compute Nodes
    # OS::TripleO::Compute::Net::SoftwareConfig: /home/centos/tripleo-heat-templates/network/config/multiple-nics/compute.yaml
    OS::TripleO::Compute::Net::SoftwareConfig: /home/centos/overcloud/templates/compute.yaml
    # OS::TripleO::ComputeLeaf1::Net::SoftwareConfig: /home/centos/tripleo-heat-templates/network/config/multiple-nics/compute.yaml
    OS::TripleO::ComputeLeaf1::Net::SoftwareConfig: /home/centos/overcloud/templates/compute.yaml

