- hosts: undercloud
  tasks:
  - name: Set up some swap space
    become: yes
    shell:
      sudo dd if=/dev/zero of=/opt/8GB.swap bs=8192 count=1048576
      sudo mkswap /opt/8GB.swap
      sudo swapon /opt/8GB.swap
      echo "/opt/8GB.swap swap                                    swap    defaults 0 0" >> /etc/fstab
  - name: Install tripleo repos rpm
    become: yes
    yum:
      name: https://trunk.rdoproject.org/centos7/current/python2-tripleo-repos-0.0.1-0.20181023065245.b124753.el7.noarch.rpm
      state: present
  - name: Set up tripleo repos
    become: yes
    shell:
      tripleo-repos current-tripleo-dev
  - name: upgrade all packages
    become: yes
    yum:
      name: '*'
      state: latest
  - name: Install packages
    become: yes
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - git
        - tmux
        - vim-enhanced
        - python-tripleoclient
  - name: Git checkout ooo-bp-tripleo-routed-networks-templates-testing
    git:
      repo: https://github.com/hjensas/ooo-bp-tripleo-routed-networks-templates-testing.git
      dest: "{{ ansible_env.HOME }}/ooo-bp-tripleo-routed-networks-templates-testing"
  - name: Git checkout tripleo-heat-templates
    git:
      repo: git://git.openstack.org/openstack/tripleo-heat-templates
      dest: "{{ ansible_env.HOME }}/tripleo-heat-templates"
      refspec: refs/changes/59/613459/4
      version: FETCH_HEAD
  - name: Git checkout python-tripleoclient
    git:
      repo: git://git.openstack.org/openstack/python-tripleoclient
      dest: "{{ ansible_env.HOME }}/python-tripleoclient"
      refspec: refs/changes/87/613487/2
      version: FETCH_HEAD
  - name: Patch python-tripleoclient
    become: yes
    shell:
      cp {{ ansible_env.HOME }}/python-tripleoclient/tripleoclient/v1/tripleo_deploy.py /usr/lib/python2.7/site-packages/tripleoclient/v1/tripleo_deploy.py
  - name: Create symlinks
    file:
      src: "{{ ansible_env.HOME }}/ooo-bp-tripleo-routed-networks-templates-testing/{{ item }}"
      dest: "{{ ansible_env.HOME }}/{{ item }}"
      state: link
    with_items:
      - overcloud
      - undercloud.conf
      - containers-prepare-parameter.yaml
  - name: Create images directory
    file:
      dest: "{{ ansible_env.HOME }}/images"
      state: directory
  - name: Build Images
    shell: |
      cd {{ ansible_env.HOME }}/images
      export DIB_YUM_REPO_CONF="/etc/yum.repos.d/delorean*"
      openstack overcloud image build
  - name: Install Undercloud
    shell:
      openstack undercloud install
  - name: Upload overcloud images
    shell: |
      source {{ ansible_env.HOME }}/stackrc
      cd {{ ansible_env.HOME }}/images
      openstack overcloud image upload
  - name: Import nodes
    shell: |
      source {{ ansible_env.HOME }}/stackrc
      openstack overcloud node import instackenv.json
  - name: Introspect and provide nodes
    shell: |
      source {{ ansible_env.HOME }}/stackrc
      openstack overcloud node introspect --all-manageable --provide
  - name: Create flavors and set node capabilities
    shell: |
      source {{ ansible_env.HOME }}/stackrc
      bash {{ ansible_env.HOME }}/overcloud/set_capabilities
